#!/usr/bin/env bash
# =============================================================================
# TMV Startup Script
# Tengu Marauder Vanguard
#
# Detects which hardware devices are present on this host, generates a
# compose override, and starts the container with only the devices that exist.
# This prevents Docker from refusing to start when optional hardware
# (camera, ESP32, motor hat) is not connected.
#
# Usage:
#   ./tmv-start.sh              # start (detached)
#   ./tmv-start.sh --logs       # start and follow logs
#   ./tmv-start.sh --stop       # stop the container
#   ./tmv-start.sh --rebuild    # rebuild image then start
# =============================================================================
set -euo pipefail

OVERRIDE="compose.override.yaml"

# ── Argument handling ──────────────────────────────────────────────────────────
case "${1:-}" in
  --stop)
    echo "[*] Stopping TMV..."
    docker compose down
    exit 0
    ;;
  --rebuild)
    echo "[*] Rebuilding TMV image..."
    docker compose build
    ;;
  --logs)
    FOLLOW_LOGS=true
    ;;
  "")
    FOLLOW_LOGS=false
    ;;
  *)
    echo "Usage: $0 [--logs | --stop | --rebuild]"
    exit 1
    ;;
esac

# ── Device detection ───────────────────────────────────────────────────────────
# List of candidate devices to check. Docker will refuse to start if any
# mapped device doesn't exist on the host, so we only map what's present.
declare -A DEVICE_LABELS=(
  ["/dev/video0"]="USB webcam"
  ["/dev/ttyUSB0"]="Serial USB (ESP32 Marauder / Bruce)"
  ["/dev/ttyACM0"]="Serial ACM (Flipper Zero / alternate)"
  ["/dev/i2c-1"]="I2C bus 1 (motor hat)"
  ["/dev/rfkill"]="RF kill switch"
  ["/dev/hci0"]="Bluetooth HCI"
)

echo "[*] Detecting hardware devices..."

FOUND_DEVICES=()
for dev in "${!DEVICE_LABELS[@]}"; do
  if [ -e "$dev" ]; then
    echo "  [+] $dev — ${DEVICE_LABELS[$dev]}"
    FOUND_DEVICES+=("$dev")
  else
    echo "  [~] $dev — not present (${DEVICE_LABELS[$dev]})"
  fi
done

echo

# ── Generate compose override ─────────────────────────────────────────────────
if [ ${#FOUND_DEVICES[@]} -eq 0 ]; then
  # No devices found — write a minimal no-op override
  cat > "$OVERRIDE" << 'EOF'
# Generated by tmv-start.sh — no hardware devices detected
services:
  tmv: {}
EOF
  echo "[~] No hardware devices found — starting without device access"
else
  # Write override with detected devices
  cat > "$OVERRIDE" << 'EOF'
# Generated by tmv-start.sh — do not edit manually
services:
  tmv:
    devices:
EOF
  for dev in "${FOUND_DEVICES[@]}"; do
    echo "      - \"${dev}:${dev}\"" >> "$OVERRIDE"
  done
  echo "[*] Mapped ${#FOUND_DEVICES[@]} device(s) into container"
fi

echo

# ── Start container ────────────────────────────────────────────────────────────
echo "[*] Starting TMV..."
docker compose -f compose.yaml -f "$OVERRIDE" up -d

echo
echo "[+] TMV is running — http://$(hostname -I | awk '{print $1}'):5000"
echo "[+] Logs: docker compose logs -f"
echo "[+] Stop: ./tmv-start.sh --stop"
echo

if [ "${FOLLOW_LOGS:-false}" = "true" ]; then
  docker compose logs -f
fi
