#!/usr/bin/env bash
# =============================================================================
# TMV Startup Script
# Tengu Marauder Vanguard
#
# Detects which hardware devices are present on this host, generates a
# compose override, and starts the container with only the devices that exist.
# This prevents Docker from refusing to start when optional hardware
# (camera, ESP32, motor hat) is not connected.
#
# Usage:
#   ./tmv-start.sh              # start (detached)
#   ./tmv-start.sh --logs       # start and follow logs
#   ./tmv-start.sh --stop       # stop the container
#   ./tmv-start.sh --rebuild    # rebuild image then start
# =============================================================================
set -uo pipefail

OVERRIDE="compose.override.yaml"

# ── Argument handling ──────────────────────────────────────────────────────────
case "${1:-}" in
  --stop)
    echo "[*] Stopping TMV..."
    docker compose down
    exit 0
    ;;
  --rebuild)
    echo "[*] Rebuilding TMV image..."
    docker compose build
    ;;
  --logs)
    FOLLOW_LOGS=true
    ;;
  "")
    FOLLOW_LOGS=false
    ;;
  *)
    echo "Usage: $0 [--logs | --stop | --rebuild]"
    exit 1
    ;;
esac

# ── Device detection ───────────────────────────────────────────────────────────
# Fixed candidate devices to check:
declare -A DEVICE_LABELS=(
  ["/dev/video0"]="USB webcam"
  ["/dev/ttyUSB0"]="Serial USB (ESP32 Marauder / Bruce)"
  ["/dev/ttyACM0"]="Serial ACM (Flipper Zero / alternate)"
  ["/dev/i2c-1"]="I2C bus 1 (motor hat PWM)"
  ["/dev/gpiomem"]="GPIO memory (motor direction pins)"
  ["/dev/rfkill"]="RF kill switch"
)

# ── Write override from a device list ─────────────────────────────────────────
write_override() {
  local -a devs=("$@")
  if [ ${#devs[@]} -eq 0 ]; then
    cat > "$OVERRIDE" << 'EOF'
# Generated by tmv-start.sh — no hardware devices detected
services:
  tmv: {}
EOF
  else
    cat > "$OVERRIDE" << 'EOF'
# Generated by tmv-start.sh — do not edit manually
services:
  tmv:
    devices:
EOF
    for dev in "${devs[@]}"; do
      echo "      - \"${dev}:${dev}\"" >> "$OVERRIDE"
    done
  fi
}

# ── Scan present devices ───────────────────────────────────────────────────────
scan_devices() {
  local -n _result=$1
  _result=()

  # Fixed candidates
  for dev in "${!DEVICE_LABELS[@]}"; do
    if [ -e "$dev" ]; then
      _result+=("$dev")
    fi
  done

  # Dynamic: all /dev/hci* Bluetooth adapters (hci0, hci1, …)
  for dev in /dev/hci*; do
    [ -e "$dev" ] && _result+=("$dev")
  done

  # Dynamic: all /dev/video* cameras beyond video0
  for dev in /dev/video[1-9]; do
    [ -e "$dev" ] && _result+=("$dev")
  done
}

echo "[*] Detecting hardware devices..."

declare -a FOUND_DEVICES
scan_devices FOUND_DEVICES

# Print fixed candidates
for dev in "${!DEVICE_LABELS[@]}"; do
  if [[ " ${FOUND_DEVICES[*]} " == *" $dev "* ]]; then
    echo "  [+] $dev — ${DEVICE_LABELS[$dev]}"
  else
    echo "  [~] $dev — not present (${DEVICE_LABELS[$dev]})"
  fi
done

# Print dynamically found hci/video devices
for dev in "${FOUND_DEVICES[@]}"; do
  case "$dev" in
    /dev/hci*)   echo "  [+] $dev — Bluetooth HCI adapter" ;;
    /dev/video[1-9]) echo "  [+] $dev — additional USB camera" ;;
  esac
done

echo

# ── Start with retry on missing-device error ───────────────────────────────────
# A device can vanish between detection and Docker opening it (race condition).
# If Docker reports a missing device, drop it and retry — up to 3 attempts.

MAX_RETRIES=3
attempt=0

while [ $attempt -lt $MAX_RETRIES ]; do
  attempt=$(( attempt + 1 ))

  if [ ${#FOUND_DEVICES[@]} -eq 0 ]; then
    echo "[~] No hardware devices found — starting without device access"
  else
    echo "[*] Mapped ${#FOUND_DEVICES[@]} device(s) into container"
  fi

  write_override "${FOUND_DEVICES[@]+"${FOUND_DEVICES[@]}"}"

  echo "[*] Starting TMV (attempt $attempt)..."
  DOCKER_ERR=$(docker compose -f compose.yaml -f "$OVERRIDE" up -d 2>&1)
  EXIT_CODE=$?

  if [ $EXIT_CODE -eq 0 ]; then
    break
  fi

  echo "$DOCKER_ERR" >&2

  # Extract the missing device path from the Docker error message:
  #   "error gathering device information while adding custom device "/dev/foo": no such file"
  MISSING=$(echo "$DOCKER_ERR" | grep -oP '(?<=custom device ")[^"]+' | head -1)

  if [ -z "$MISSING" ]; then
    echo "[!] Docker failed for an unrelated reason — aborting." >&2
    exit 1
  fi

  echo "[!] Device $MISSING vanished before Docker could open it — removing and retrying..."
  FOUND_DEVICES=("${FOUND_DEVICES[@]//$MISSING}")
  # Strip empty entries left by the substitution above
  local_tmp=()
  for d in "${FOUND_DEVICES[@]}"; do
    [ -n "$d" ] && local_tmp+=("$d")
  done
  FOUND_DEVICES=("${local_tmp[@]+"${local_tmp[@]}"}")
done

if [ $attempt -ge $MAX_RETRIES ] && [ $EXIT_CODE -ne 0 ]; then
  echo "[!] Failed to start TMV after $MAX_RETRIES attempts." >&2
  exit 1
fi

echo
echo "[+] TMV is running — http://$(hostname -I | awk '{print $1}'):5000"
echo "[+] Logs: docker compose logs -f"
echo "[+] Stop: ./tmv-start.sh --stop"
echo

if [ "${FOLLOW_LOGS:-false}" = "true" ]; then
  docker compose logs -f
fi
