#!/usr/bin/env bash
# =============================================================================
# TMV Host Permissions Setup
# Tengu Marauder Vanguard
#
# Run this ONCE on the Raspberry Pi host OS before using Docker.
# It fixes the root cause of "needs sudo" for hardware access:
#
#   1. Adds the current user to all hardware groups
#   2. Writes udev rules so device permissions persist across reboots
#   3. Generates the .env file with correct GIDs for compose.yaml
#
# Run as: sudo bash Install/install_host_permissions.sh
# =============================================================================
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "[!] Run with sudo: sudo bash $0" >&2
  exit 1
fi

# The user who will run Docker (the one who invoked sudo)
TARGET_USER="${SUDO_USER:-$(logname 2>/dev/null || echo ubuntu)}"
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "==================================================================="
echo " TMV Host Permissions Setup"
echo " Target user : $TARGET_USER"
echo " Project dir : $PROJECT_DIR"
echo "==================================================================="
echo

# ── 1. Ensure hardware groups exist ───────────────────────────────────────────

echo "[*] Ensuring hardware groups exist..."

for group in i2c gpio spi video dialout bluetooth plugdev input; do
  if ! getent group "$group" > /dev/null 2>&1; then
    groupadd --system "$group"
    echo "  [+] Created group: $group"
  else
    echo "  [=] Group exists: $group (GID $(getent group "$group" | cut -d: -f3))"
  fi
done

echo

# ── 2. Add user to all hardware groups ────────────────────────────────────────

echo "[*] Adding $TARGET_USER to hardware groups..."

for group in i2c gpio spi video dialout bluetooth plugdev input; do
  if id -nG "$TARGET_USER" | grep -qw "$group"; then
    echo "  [=] Already in: $group"
  else
    usermod -aG "$group" "$TARGET_USER"
    echo "  [+] Added to: $group"
  fi
done

echo

# ── 3. Write udev rules for device permissions ────────────────────────────────
# Without these, device files come up root-only even if the user is in the
# right group. These rules set the group owner and mode on every boot.

echo "[*] Writing udev rules to /etc/udev/rules.d/99-tmv-hardware.rules..."

cat > /etc/udev/rules.d/99-tmv-hardware.rules << 'EOF'
# TMV Hardware Permissions
# Generated by Install/install_host_permissions.sh
# Allows non-root access to Robot HAT, camera, serial, and Bluetooth devices.

# I2C buses (Robot HAT PCA9685 PWM controller)
SUBSYSTEM=="i2c-dev", GROUP="i2c", MODE="0660"

# GPIO memory (RPi.GPIO direction pins)
SUBSYSTEM=="bcm2835-gpiomem", GROUP="gpio", MODE="0660"
KERNEL=="gpiomem",             GROUP="gpio", MODE="0660"
KERNEL=="gpiochip*",           GROUP="gpio", MODE="0660"

# SPI buses
SUBSYSTEM=="spidev", GROUP="spi", MODE="0660"

# USB cameras (UVC)
SUBSYSTEM=="video4linux", GROUP="video", MODE="0660"

# USB serial (ESP32 Marauder, Flipper Zero, CH340, CP2102, FTDI)
SUBSYSTEM=="tty", SUBSYSTEMS=="usb", GROUP="dialout", MODE="0660"
KERNEL=="ttyUSB*", GROUP="dialout", MODE="0660"
KERNEL=="ttyACM*", GROUP="dialout", MODE="0660"

# Bluetooth HCI
SUBSYSTEM=="bluetooth", GROUP="bluetooth", MODE="0660"
KERNEL=="hci*",         GROUP="bluetooth", MODE="0660"

# RTL-SDR dongle
SUBSYSTEM=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838", GROUP="plugdev", MODE="0664"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2832", GROUP="plugdev", MODE="0664"
EOF

echo "  [+] Rules written"

# Reload udev and re-apply rules to currently present devices
udevadm control --reload-rules
udevadm trigger
echo "  [+] udev rules reloaded"

echo

# ── 4. Fix permissions on currently present devices ───────────────────────────
# udev trigger handles future devices; fix present ones immediately.

echo "[*] Applying permissions to present devices..."

fix_device() {
  local dev="$1" group="$2" mode="$3"
  if [ -e "$dev" ]; then
    chown "root:$group" "$dev" && chmod "$mode" "$dev"
    echo "  [+] $dev → group=$group mode=$mode"
  fi
}

fix_device /dev/i2c-1    i2c      660
fix_device /dev/gpiomem  gpio     660
fix_device /dev/video0   video    660
fix_device /dev/ttyUSB0  dialout  660
fix_device /dev/ttyACM0  dialout  660
fix_device /dev/hci0     bluetooth 660

# gpiochip devices (kernel 5.x+ GPIO character device)
for chip in /dev/gpiochip*; do
  [ -e "$chip" ] && fix_device "$chip" gpio 660
done

echo

# ── 5. Generate .env with correct GIDs ────────────────────────────────────────

echo "[*] Generating $PROJECT_DIR/.env with host GIDs..."

ENV_FILE="$PROJECT_DIR/.env"

get_gid() {
  getent group "$1" 2>/dev/null | cut -d: -f3
}

cat > "$ENV_FILE" << EOF
# TMV Docker group IDs — generated by Install/install_host_permissions.sh
# These must match the host groups that own the hardware device files.
# Regenerate with: sudo bash Install/install_host_permissions.sh

VIDEO_GID=$(get_gid video || echo 44)
DIALOUT_GID=$(get_gid dialout || echo 20)
I2C_GID=$(get_gid i2c || echo 998)
GPIO_GID=$(get_gid gpio || echo 997)
BLUETOOTH_GID=$(get_gid bluetooth || echo 105)
EOF

echo "  [+] Written:"
sed 's/^/      /' "$ENV_FILE"

echo

# ── 6. Verify robot_hat host access (quick sanity check) ──────────────────────

echo "[*] Checking I2C bus for Robot HAT (address 0x14 / 0x74)..."
if command -v i2cdetect > /dev/null 2>&1 && [ -e /dev/i2c-1 ]; then
  i2cdetect -y 1 2>/dev/null | grep -E "14|74" && \
    echo "  [+] Robot HAT PCA9685 detected on I2C bus 1" || \
    echo "  [~] No known HAT address found — hat may not be connected"
else
  echo "  [~] i2cdetect not available or /dev/i2c-1 absent — skipping"
fi

echo

# ── Done ──────────────────────────────────────────────────────────────────────

echo "==================================================================="
echo " Done."
echo
echo " IMPORTANT: Group changes take effect on next login."
echo " Log out and back in (or reboot), then run:"
echo
echo "   cd $PROJECT_DIR"
echo "   ./tmv-start.sh --rebuild"
echo
echo " To verify group membership without logging out:"
echo "   newgrp i2c    # opens a subshell with i2c group active"
echo "==================================================================="
